# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7ac5051d66c18a5f3dd7c225be1c6c3f527bfc3f1e4e442a1c47c377ede593921e4029d17fe4bf22f4f158b9ce49b66985f97dd240e9e8c4e643f4fd6fdb93b

test:
  secret_key_base: 64738174600bd50a0ba238618972a65480198b98e872da9b6dd7f8835b30a5e3ad6dd8e671350f0bd9d1c5f778d6ae00c33edf2583d5611cdb0eb0c468a82f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
